# This rule is not used by the project myelin itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to myelin.myelin.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: myelin
    app.kubernetes.io/managed-by: kustomize
  name: myelinsecret-viewer-role
rules:
- apiGroups:
  - myelin.myelin.io
  resources:
  - myelinsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myelin.myelin.io
  resources:
  - myelinsecrets/status
  verbs:
  - get
