---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myelin.myelin.io
  resources:
  - myelinsecretpolicies
  - myelinsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myelin.myelin.io
  resources:
  - myelinsecretpolicies/finalizers
  - myelinsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - myelin.myelin.io
  resources:
  - myelinsecretpolicies/status
  - myelinsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
