apiVersion: myelin.myelin.io/v1alpha1
kind: MyelinSecretPolicy
metadata:
  labels:
    app.kubernetes.io/name: myelin
    app.kubernetes.io/managed-by: kustomize
  name: myelinsecretpolicy-sample
spec:
  # TODO(user): Add fields here
